// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPocatek.Data;

#nullable disable

namespace WebPocatek.Data.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    partial class ToDoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebPocatek.Data.Ukol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Hotovo")
                        .HasColumnType("bit");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("Popis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Termin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ukoly");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hotovo = false,
                            Nazev = "Nakoupit",
                            Popis = "3 rohlíky, 1/2 chleba",
                            Termin = new DateTime(2022, 11, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Hotovo = false,
                            Nazev = "Uklidit",
                            Popis = "Doma a venku",
                            Termin = new DateTime(2022, 11, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Hotovo = false,
                            Nazev = "Opravit kolo",
                            Popis = "Je tam díra",
                            Termin = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Hotovo = false,
                            Nazev = "Vytvořit si web",
                            Popis = "Vlastní web s kontakty na mě"
                        },
                        new
                        {
                            Id = 5,
                            Hotovo = true,
                            Nazev = "Přečíst si knihu",
                            Termin = new DateTime(2022, 11, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            Hotovo = true,
                            Nazev = "Úkol z matematiky",
                            Termin = new DateTime(2022, 10, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
